#!/bin/bash
echo -e " "
echo -e " ${z}╭══════════════════════════════════════════════════════════╮${NC}"
echo -e " ${z}│$NC${f}     WELCOME TO  HOKAGE LEGEND AUTOSCRIPT PREMIUM      $NC${z}│$NC"
echo -e " ${z}╰══════════════════════════════════════════════════════════╯${NC}"


